### ISSUE TITLE
Add LocalOutputOperator

### ISSUE THREAD

**Issue by kreczko** [FAST-HEP/fasthep-flow#14]
It is nice to be able to run commands and functions, but we also need the ability to store it.
This issue is part of a set of others which will include logging, remote output, other output formats etc.

To start, we can base it on https://docs.prefect.io/latest/concepts/filesystems/?h=files#local-filesystem.

For the config, this should be similar to
```
- name: Output data
  type: fasthep_carpenter.operators.LocalOutputOperator
  kwargs:
    path: "/path/to/output/out.txt"
    type: text
  ```
It should only output the result of the previous stage for now
