### ISSUE TITLE
Common aliases

### ISSUE THREAD

**Issue by kreczko** [FAST-HEP/fasthep-flow#54]
FAST-HEP itself will consist of several python packages:

![Image](https://github.com/user-attachments/assets/d73e4822-b567-42f0-aa36-38b784dcf41b)

As a result, config files might become a bit lengthy.

It might be worth to introduce a common shorthand that do not clash with other package names or got for consistency?:
- `fasthep-gitlab` &rarr; `fh.gitlab` (might be confused with `gitlab` package otherwise)
- `fasthep-carpenter` &rarr; `carpenter`
- `fasthep-flow` &rarr; `flow`
- `fasthep-core` &rarr; `core`
- `fasthep-contrib` &rarr; `contrib`
- `fasthep-artist` &rarr; `artist`
- `fasthep-stats` &rarr; `stats`
- `fasthep-validate` &rarr; `validate`

Of course, aliases will always be configurable - any user could construct their own.

**Comment by kreczko** [comment]
This has now been solved with registries. E.g.
```yaml
registry:
  sources:
    root_tree:
      spec: fasthep_carpenter.spec.read.root_tree:ROOT_TREE_SOURCE_SPEC
      impl: fasthep_carpenter.impl.read.root_tree:run_root_tree_source

    hep.define:
      spec: fasthep_carpenter.spec.define_transform:DEFINE_TRANSFORM_SPEC
      impl: fasthep_carpenter.impl.define:run_define_transform
```

What is left to do is detect and track an overwrite of values. External packages can also declare registries and export them as profiles:
```
use:
  profiles:
    - ./profiles/local.yaml
```
or
```
use:
  profiles:
    - registry
    - fasthep_carpenter:registry
    - fasthep_curator:registry
```
