### ISSUE TITLE
Workflow converter: gitlab-ci

### ISSUE THREAD

**Issue by kreczko** [FAST-HEP/fasthep-flow#56]
Once #48 is done, we can implement a converter for `fasthep.workflow` &rarr; gitlab-ci.yml, e .g.
```yaml
# simple_config.yml
tasks:
  - name: printEcho
    type: "fasthep_flow.operators.BashOperator"
    kwargs:
      bash_command: echo
      arguments: ["Hello World!"]
```
&rarr;
```yaml
variables:
  FASTHEP_CONFIG: path/to/simple_config.yml

setup:
  script:
    - install uv
    - uv venv --python-3.11
    - uv pip install .
  artifacts:
    paths:
      - .venv

task_printEcho:
  needs: [setup]
  script: 
    - uv run fasthep-flow execute $FASTHEP_CONFIG --task printEcho --save-path output | tee printEcho.log
  artifacts:
    paths:
      - printEcho.log
      - output
```

Similar converters will come for `Snakemake`, then REANA (via Snakemake)
