### ISSUE TITLE
Multi-step selections

### ISSUE THREAD

**Issue by jeronimo-bris** [FAST-HEP/fasthep-flow#61]
Hi it would be nice if it were possible to implement more than one set of selections. Specifically for computationally expensive tasks like using ML classifiers it seems a bit wasteful to have to apply this to events which you know will fail any of your other selections. Ideally it would be possible to do something along the lines of the following:

1. do some initial selections on simple variables (e.g. cut on jet_pt or MET)
2. remove any events which dont pass this selection
3. apply classifier (or other modules) to remaining events
4. apply final selections which depend on previous step (e.g. cut on classifier score)
5. histogram / other downstream task with final subset of events

**Comment by kreczko** [comment]
In the current setup, we have parallel configs. I am planning to have each task check its dependencies for filters. If any are found, they are applied:
```
tasks:
  - name: "A"
    type: "fasthep_flow.operators.BashOperator"
    kwargs:
      bash_command: echo
      arguments: ["A"]
  - name: "B"
    type: "fasthep_flow.operators.BashOperator"
    kwargs:
      bash_command: echo
      arguments: ["B"]
  - name: "C"
    type: "fasthep_flow.operators.BashOperator"
    kwargs:
      bash_command: echo
      arguments: ["C"]
    needs:
      - "A"
  - name: "D"
    type: "fasthep_flow.operators.BashOperator"
    kwargs:
      bash_command: echo
      arguments: ["D"]
    needs:
      - "B"
  - name: "Y"
    type: "fasthep_flow.operators.BashOperator"
    kwargs:
      bash_command: echo
      arguments: ["Y"]
    needs:
      - "C"
      - "D"
```
This creates the following workflow:
![Image](https://github.com/user-attachments/assets/e2e23aeb-c930-4893-ac72-e3268803d489)

In that image, A and B could be independent and you could have a whole hierarchy of selections.
The cuts would be applied in the order things are defined in `needs`. Is this enough or do you require "tagging"? I.e. marking events if they pass or not, but do not filter.

**Comment by kreczko** [comment]
Ok, putting it into docs now, this should satisfy your needs:
```yaml
tasks:
  ...
  event_selection:
    type: fasthep_flow.Filter
    kwargs:
      selection:
        All:
          - MET >= 200
          - njet >= 4
          - Any:
              - nelectron > 0
              - nmuon > 0
  control_region:
    type: fasthep_flow.Filter
    kwargs:
      selection:
        All:
          - MET < 200
          - njet > 2
          - njet < 4
          - Any:
              - nelectron == 1
              - nmuon == 1
  signal_task:
    type: fasthep_carpenter.Histogram
    needs: [event_selection]
    kwargs:
      inputs: 
        - MET
        - njet
      bins:
        - MET: [0, 100, 200, 300]
        - njet: [4, 5, 6, 7]
      overflow: True
  control_task:
    type: fasthep_carpenter.Histogram
    needs: [control_region]
    kwargs:
      inputs: 
        - MET
        - njet
      bins:
        - MET: [0, 100, 200]
        - njet: [2, 3]
      overflow: True  
  ...
    # The rest of the tasks
```
This will produce two histograms, one for the signal region and one for the control region. The workflow will look like this:

```mermaid
flowchart LR
    subgraph Data task
    A[read data]
    end
    subgraph Filter tasks
    B[event_selection]
    C[control_region]
    end
    subgraph Histogram tasks
    signal_hf1[signal_task]
    control_hf1[control_task]
    end
    subgraph Output tasks
    out[write output]
    end
    A --> B
    A --> C
    B --> signal_hf1
    C --> control_hf1
    signal_hf1 --> out
    control_hf1 --> out

```

Technically nothing would stop you from putting processing tasks in between to do your ML classifier calculation. 
Please let me know if that will work for you or if I've missed an important point.
If it looks good, I will start on it after #55.

Note: this project is still in a very early stage, so don't expect this to work any time soon. I am now regularly working on it, but it will take a few more months before it is ready for first trials. In the meantime I am trying to understand user requirements, which I've coded into imaginary docs: https://fasthep-flow.readthedocs.io/en/latest/

**Comment by jeronimo-bris** [comment]
I think what you describe should work. The "tagging" functionality would also be useful, primarily for debugging cuts etc, but this can also be done in fast_carpenter by simply defining a new branch. Having it as an output of the selections if a "filter" is not applied would be neater though.

**Comment by kreczko** [comment]
In the end, I introduced the `from: ` keyword.
e.g.
```yaml
- id: Preselection
      op: hep.selection.cutflow
      from: DefineLeptons
      params:
        selection:
          All:
            - "MET_pt > 200"
            - nJet >= 4
      out:
        events: events
        cutflow: cutflow

...
- id: AtLeast1TightElectron
      op: hep.selection.cutflow
      from: Preselection
      params:
        selection:
          All:
            - "nTightElectrons >= 1"
      out:
        events: events
        cutflow: cutflow

- id: H_nJet_1TightElectron
      op: hep.hist
      from: AtLeast1TightElectron
      params:
        dataset_axis: true
        axes:
          - {name: nJet, source: nJet, type: regular, bins: {low: 0, high: 15, nbins: 15}}
      render:
        style:
          use: njet_count
          with:
            axes:
              x: {name: nJet, label: "Number of jets (>=1 tight electron)", limits: [0, 15]}
        when: final
        out: H_nJet_1TightElectron.png
```

```mermaid
flowchart TD
  read_events["read.events<br/>source<br/>root_tree"]
  project_events["project.events<br/>transform<br/>hep.project_fields"]
  stage_nominal_weight["stage.nominal_weight<br/>transform<br/>hep.define"]
  stage_JetVars["stage.JetVars<br/>transform<br/>hep.define"]
  stage_common_selection["stage.common_selection<br/>transform<br/>hep.selection.cutflow"]
  write_common_selection_0["write.common_selection.0<br/>sink<br/>root_tree"]
  stage_NumberOfLooseMuons["stage.NumberOfLooseMuons<br/>transform<br/>hep.hist"]
  render_NumberOfLooseMuons_0["render.NumberOfLooseMuons.0<br/>sink<br/>hep.render.data_mc"]
  stage_NumberOfTightMuons["stage.NumberOfTightMuons<br/>transform<br/>hep.hist"]
  render_NumberOfTightMuons_0["render.NumberOfTightMuons.0<br/>sink<br/>hep.render.data_mc"]
  stage_SingleMuonCR["stage.SingleMuonCR<br/>transform<br/>hep.selection.cutflow"]
  stage_DiMuonCR["stage.DiMuonCR<br/>transform<br/>hep.selection.cutflow"]
  stage_NumberOfJets_SingleMuonCR["stage.NumberOfJets_SingleMuonCR<br/>transform<br/>hep.hist"]
  render_NumberOfJets_SingleMuonCR_0["render.NumberOfJets_SingleMuonCR.0<br/>sink<br/>hep.render.data_mc"]
  stage_NumberOfJets_DiMuonCR["stage.NumberOfJets_DiMuonCR<br/>transform<br/>hep.hist"]
  render_NumberOfJets_DiMuonCR_0["render.NumberOfJets_DiMuonCR.0<br/>sink<br/>hep.render.data_mc"]
  read_events -->|stream -> stream| project_events
  project_events -->|stream -> stream| stage_nominal_weight
  stage_nominal_weight -->|stream -> stream| stage_JetVars
  stage_JetVars -->|stream -> stream| stage_common_selection
  stage_common_selection -->|stream -> target| write_common_selection_0
  stage_common_selection -->|stream -> stream| stage_NumberOfLooseMuons
  stage_common_selection -->|stream -> stream| stage_NumberOfTightMuons
  stage_common_selection -->|stream -> stream| stage_SingleMuonCR
  stage_common_selection -->|stream -> stream| stage_DiMuonCR
  stage_NumberOfLooseMuons -->|hist -> target| render_NumberOfLooseMuons_0
  stage_NumberOfTightMuons -->|hist -> target| render_NumberOfTightMuons_0
  stage_SingleMuonCR -->|stream -> stream| stage_NumberOfJets_SingleMuonCR
  stage_DiMuonCR -->|stream -> stream| stage_NumberOfJets_DiMuonCR
  stage_NumberOfJets_SingleMuonCR -->|hist -> target| render_NumberOfJets_SingleMuonCR_0
  stage_NumberOfJets_DiMuonCR -->|hist -> target| render_NumberOfJets_DiMuonCR_0
```
