### ISSUE TITLE
Plugin: aliases

### ISSUE THREAD

**Issue by kreczko** [FAST-HEP/fasthep-flow#64]
A port of https://github.com/FAST-HEP/fast-carpenter/issues/5.

Aliasing is a very useful feature, especially when working with meaningful names, e.g. `Events;1.recoGenJets_slimmedGenJetsAK8SoftDropSubJets__PAT`. Accessing them as `ak8genjets` (or whatever makes sense in the context of the analysis), can make other code more concise.

This plugin should have both a global config and a per-task config (e.g. local aliases).

**Comment by kreczko** [comment]
Done, aliases are now set via `fields`:
```yaml
fields:
  ss_nSingleScatters: {stream: scatters, branch: "ss./ss.nSingleScatters"}
  s1_phd:             {stream: scatters, branch: "ss./ss.s1Area_phd"}
  s2_raw:             {stream: scatters, branch: "ss./ss.s2Area_phd"}
  s2_corrected:       {stream: scatters, branch: "ss./ss.correctedS2Area_phd"}
  s2_xy_corrected:    {stream: scatters, branch: "ss./ss.correctedS2Area_phd"}
  s2_x:               {stream: scatters, branch: "ss./ss.correctedX_cm"}
  s2_y:               {stream: scatters, branch: "ss./ss.correctedY_cm"}
```
