### ISSUE TITLE
Implement simple_config

### ISSUE THREAD

**Issue by kreczko** [FAST-HEP/fasthep-flow#8]
The most simple config for this project is
```yaml
stages:
  - name: printEcho
    type: "fasthep_flow.operators.BashOperator"
    kwargs:
      bash_command: echo
      arguments: ["Hello World!"]
```

The features needed:
- basic YAML parsing to construct `FlowConfig`
- basic workflow that uses prefect.task and prefect.flow to construct a graph
- ability to execute workflow on a local machine
